[package]
name = "Advent of Code 2017"
version = "0.1.0"
authors = ["Andreas Neuhaus <zargony@zargony.com>"]
description = "Solutions to the Advent of Code 2017 puzzles"

[dependencies]

[[bin]]
name = "day01"
path = "src/day01.rs"
